name: team09/lebenslauf
typeName: team09_lebenslauf
group: default
prefixFields: true
prefixType: full
fields:
  -
    identifier: header
    useExistingField: true
    label: "header.label"

  -
    identifier: person
    type: Tab
    label: "tabs.person"

  - identifier: vorname
    type: Text
    label: "vorname.label"
    required: true

  -
    identifier: nachname
    type: Text
    label: "nachname.label"
    required: true

  -
    identifier: strasse
    type: Text
    label: "strasse.label"

  - identifier: plz
    type: Text
    label: "plz.label"

  - identifier: ort
    type: Text
    label: "ort.label"

  - identifier: geburtsdatum
    type: Text
    label: "geburtsdatum.label"

  - identifier: lebenslauf
    type: Tab
    label: "tabs.lebenslauf"

  - identifier: stationen
    type: Collection
    label: "stationen.label"
    labelField: title
    appearance.useSortable: true
    appearance.collapseAll: true
    fields:
      - identifier: startdate
        type: Text
        label: "startdate.label"
        required: true
      - identifier: enddate
        type: Text
        label: "enddate.label"
      - identifier: title
        type: Text
        label: "title.label"
        required: true
      - identifier: company
        type: Text
        label: "company.label"
        required: true
      - identifier: description
        type: Textarea
        label: "description.label"
