name: team09/lebenslauf
typeName: team09_lebenslauf
group: default
prefixFields: true
prefixType: full
fields:
  -
    identifier: header
    useExistingField: true
    label: "header.label"

  -
    identifier: person
    type: Tab
    label: "Persönliche Daten"

  - identifier: vorname
    type: Text
    label: "Vorname"
    required: true

  -
    identifier: nachname
    type: Text
    label: "Nachname"
    required: true

  -
    identifier: strasse
    type: Text
    label: "Straße"

  - identifier: plz
    type: Text
    label: "PLZ"

  - identifier: ort
    type: Text
    label: "Ort"

  - identifier: geburtsdatum
    type: Text
    label: "Geburtsdatum"

  - identifier: erfahrungen_tab
    type: Tab
    label: "Praktische Erfahrungen"

  - identifier: erfahrungen
    type: Collection
    label: "Erfahrungseinträge"
    labelField: title
    appearance.useSortable: true
    appearance.collapseAll: true
    fields:
      - identifier: startdate
        type: Text
        label: "Startzeitpunkt (z.B. MM/JJJJ)"
        required: true
      - identifier: enddate
        type: Text
        label: "Endzeitpunkt (leer lassen für 'Heute')"
      - identifier: title
        type: Text
        label: "Position / Jobbezeichnung"
        required: true
      - identifier: company
        type: Text
        label: "Unternehmen / Organisation"
        required: true
      - identifier: description
        type: Textarea
        label: "Beschreibung der Tätigkeiten"

  - identifier: bildung_tab
    type: Tab
    label: "Schulbildung / Studium"

  - identifier: bildung
    type: Collection
    label: "Bildungseinträge"
    labelField: title
    appearance.useSortable: true
    appearance.collapseAll: true
    fields:
      - identifier: startdate
        type: Text
        label: "Startzeitpunkt"
        required: true
      - identifier: enddate
        type: Text
        label: "Endzeitpunkt"
      - identifier: title
        type: Text
        label: "Abschluss / Studiengang"
        required: true
      - identifier: institution
        type: Text
        label: "Schule / Universität"
        required: true

  - identifier: kenntnisse_tab
    type: Tab
    label: "Besondere Kenntnisse"

  - identifier: kenntnisse
    type: Collection
    label: "Kenntnisse"
    labelField: skill
    appearance.useSortable: true
    appearance.collapseAll: true
    fields:
      - identifier: skill
        type: Text
        label: "Fähigkeit (z.B. TYPO3, Englisch)"
        required: true
      - identifier: level
        type: Text
        label: "Niveau (z.B. Fortgeschritten, Muttersprache)"
